# Copyright 2019-2022 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: 'Prepare Environment'
description: 'installs pnpm, installs all deps in each package'
  
runs:
  using: "composite"
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Setup Node
    uses: setup-node@v2
    with:
      node-version: 16
  - name: Install PNPM and Dependencies
    run: |
      npm i -g pnpm
      pnpm install --ignore-scripts
      cd packages/tauri-search
      pnpm install --ignore-scripts
      cd ../docs
      pnpm install --ignore-scripts
      cd ..
  - name: Build CLI and NPM exports
    run: pnpm run build
  - name: Env Prepped
    run: echo Node, pnpm, and all deps are installed!